version: "3.8"

services:
  nginx:
    restart: unless-stopped
    build:
      context: .
      dockerfile: compose/nginx/Dockerfile
    container_name: nginx
    ports:
      - 80:80
    depends_on:
      - web
  web:
    restart: unless-stopped
    build:
      context: .
      dockerfile: compose/django/Dockerfile
    container_name: django
    volumes:
      - ./:/home/django/app/
    expose:
      - 8000
    env_file:
      - .env
